'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const dictionary = {
  ua: {
    catalogue: 'Каталог',
    contacts: 'Контакти',
    sale: 'Розпродаж',
    searchPlaceholder: 'Пошук товарів, брендів...',
    searchButton: 'Пошук',
    signUp: 'Зареєструватися',
    favorites: 'Обране',
    myProfile: 'Мій кабінет',
    logOut: 'Вийти',
    logIn: 'Увійти',
    
    // Auth & Sign Up Form Keys
    signUpTitle: 'Реєстрація',
    emailLabel: 'Електронна пошта',
    emailPlaceholder: 'example@email.com',
    phoneNumberLabel: 'Номер телефону',
    phoneNumberPlaceholder: '+380991234567',
    passwordLabel: 'Пароль',
    passwordPlaceholder: '••••••••',
    confirmPasswordLabel: 'Підтвердження паролю',
    confirmPasswordPlaceholder: '••••••••',
    userAgreementLink: 'Я приймаю Угоду користувача',
    privacyPolicyLink: 'Я погоджуюсь з Політикою конфіденційності',
    confirmBtn: 'Зареєструватися',
    alreadyHaveAccount: 'Вже є акаунт?',
    logInAction: 'Увійти',
    logInTitle: 'Вхід',
    rememberMe: 'Запам’ятати мене',
    forgotPassword: 'Забули пароль?',
    loginSuccess: 'Вхід успішний',
    loginFailed: 'Невірний email або пароль',
    loginError: 'Сталася помилка під час входу',
    registrationFailed: 'Помилка реєстрації.',
    registrationError: 'Сталася помилка під час реєстрації',
    loadingText: 'Завантаження...',

    // Buyer Profile Panel Sidebar
    personalData: 'Особисті дані',
    myOrders: 'Мої замовлення',
    cartMenu: 'Кошик',
    message: 'Повідомлення',
    wishlist: 'Список бажань',
    productsToCompare: 'Порівняння товарів',
    payment: 'Оплата',
    settings: 'Налаштування',
    helpCenter: 'Підтримка та FAQ',

    // Seller Dashboard Menu
    sellerHome: 'Головна панель',
    sellerProducts: 'Товари',
    sellerOrders: 'Замовлення',
    sellerChat: 'Чат із покупцями',
    sellerReviews: 'Відгуки',
    sellerNotifications: 'Сповіщення',
    sellerSettings: 'Налаштування профілю',
    sellerManagers: 'Менеджери',
    sellerPromotions: 'Акції',
    sellerSupport: 'Технічна підтримка',

    // Seller Cabinet Translations (UA)
    sellerGeneralOverview: 'Загальний огляд',
    last30days: 'Останні 30 днів',
    last7days: 'Останні 7 днів',
    numberOfOrders: 'Кількість замовлень',
    storeRating: 'Рейтинг магазину',
    storeViews: 'Перегляди',
    storePageViews: 'Перегляди сторінки магазину',
    productViews: 'Перегляди товарів',
    interaction: 'Взаємодія',
    addedToCart: 'Додано в кошик',
    ordersPlaced: 'Оформлено замовлень',
    incomeUah: 'Дохід, грн',
    generalInformation: 'Загальна інформація',
    period: 'Період',
    incomeAmount: 'Сума доходу',
    itemsSold: 'Кількість проданих товарів',
    activeOrdersCount: 'Кількість активних замовлень',
    completedOrdersCount: 'Кількість виконаних замовлень',
    export: 'Експорт',
    allProducts: 'Всі товари',
    deleteSelected: 'Видалити вибране',
    filter: 'Фільтр',
    sort: 'Сортування',
    addProduct: 'Додати товар',
    productName: 'Назва товару',
    productCode: 'Код товару',
    remainder: 'Залишок',
    options: 'Опції',
    implementationStatus: 'Статус реалізації',
    showMore: 'Показати більше',
    back: 'Назад',
    editProduct: 'Редагувати товар',
    variations: 'Варіанти',
    chooseColor: 'Оберіть колір',
    chooseSize: 'Оберіть розмір',
    deactivate: 'Деактивувати',
    update: 'Оновити',
    availableToOrder: 'Доступно для замовлення',
    review: 'На перевірці',
    outOfStock: 'Немає в наявності',
    createOrder: 'Створити замовлення',
    client: 'Клієнт',
    orderNumber: 'Номер замовлення',
    description: 'Опис',
    delivery: 'Доставка',
    paymentStatus: 'Оплата',
    commentOnOrder: 'Коментар до замовлення',
    unpaid: 'Неоплачено',
    paid: 'Оплачено',
    newOrder: 'Нове',
    delivered: 'Доставлено',
    completed: 'Виконано',
    clientInfo: 'Інформація про клієнта',
    deliveryAddress: 'Адреса доставки',
    country: 'Країна',
    cityVillage: 'Місто/Село',
    address: 'Адреса',
    novaPoshtaBranch: 'Відділення Нової Пошти',
    quantityPcs: 'Кількість шт',
    size: 'Розмір',
    color: 'Колір',
    total: 'Всього',
    allChats: 'Всі чати',
    sendAMessage: 'Напишіть повідомлення...',
    selectChatToStart: 'Оберіть чат для початку',
    chooseChatFromList: 'Оберіть діалог зі списку, щоб почати листування.',
    send: 'Надіслати',
    positiveScore: 'Позитивні відгуки',
    ratingDetailsByReviews: 'Деталі рейтингу за відгуками',
    periodTable: 'Період',
    oneMonth: '1 місяць',
    sixMonths: '6 місяців',
    twelveMonths: '12 місяців',
    positiveReviews: 'Позитивні',
    neutralReviews: 'Нейтральні',
    negativeReviews: 'Негативні',
    replyToCustomer: 'Відповісти покупцеві...',
    reply: 'Відповісти',
    you: 'Ви',
    clearAll: 'Очистити все',
    noNotifications: 'Немає сповіщень',
    companyInfo: 'Інформація про компанію',
    companyName: 'Назва компанії',
    aboutCompany: 'Про компанію',
    additionalInformation: 'Додаткова інформація',
    businessType: 'Тип бізнесу',
    employeesCount: 'Кількість співробітників',
    foundationYear: 'Рік заснування',
    location: 'Розташування',
    settingsSaved: 'Налаштування профілю збережено!',
    saving: 'Збереження...',
    addManager: 'Додати менеджера',
    role: 'Роль',
    remove: 'Видалити',
    createPromotion: 'Створити акцію',
    validityPeriod: 'Термін дії',
    value: 'Значення',
    actions: 'Дії',
    choosePromoType: 'Оберіть тип акції',
    basicInformation: 'Основна інформація',
    startDate: 'Дата початку',
    endDate: 'Дата закінчення',
    technicalSupport: 'Технічна підтримка',
    contactUs: "Зв'язатися з нами",
    faq: 'FAQ',
    planned: 'Заплановано',
    active: 'Активно',
    edit: 'Редагувати',
    delete: 'Видалити',
    producer: 'Виробник',
    trader: 'Торгова компанія',
    callCenter: 'Колл-центр',
    telegramChat: 'Чат Telegram',
    whatsappChat: 'Чат WhatsApp',
    visibility: 'Видимість',
    published: 'Опубліковано',
    draft: 'Чернетка',
    hidden: 'Приховано',
    initialQty: 'Початкова кількість',
    soldQty: 'Продано одиниць',
    stockAvailability: 'Наявність на складі',
    productRating: 'Рейтинг товару',
    season: 'Сезон',
    material: 'Матеріал',
    imageUploadTitle: 'Головне зображення',
    imageUploadTip: 'Перетягніть або натисніть, щоб завантажити',


    // Personal Data Page & Form Editing
    userData: 'Персональні дані',
    addressData: 'Адреса доставки',
    dateOfBirth: 'Дата народження',
    profilePhone: 'Телефон',
    profileName: 'Ім\'я',
    profileEmail: 'Електронна пошта',
    country: 'Країна',
    city: 'Місто',
    address: 'Вулиця та будинок',
    cancelBtn: 'Скасувати',
    saveBtn: 'Зберегти',
    loadingProfile: 'Завантаження профілю...',

    // Cart Page
    emptyCartTitle: 'Ваш кошик порожній',
    emptyCartDesc: 'Схоже, ви ще не додали жодного товару до кошика',
    goToShopping: 'Перейти до покупок',
    allItems: 'Всі товари',
    summary: 'Підсумок',
    subtotal: 'Вартість',
    discount: 'Знижка',
    total: 'Всього',
    checkoutTitle: 'Оформити замовлення',
    deleteItemTitle: 'Видалити товар?',
    deleteItemDesc: 'Ви впевнені, що хочете видалити цей товар з кошика?',
    deleteItemYes: 'Так, видалити',
    deleteItemNo: 'Ні, залишити',
    viewedProducts: 'Переглянуті товари',
    noViewedProducts: 'Немає переглянутих товарів',

    // Wishlist Page
    wishlistEmptyTitle: 'Ваш список бажань порожній',
    wishlistEmptyDesc: 'Сюди потраплятимуть товари, які ви позначили серцем',
    catalogueBtn: 'Перейти до каталогу',
    shareWishlist: 'Поділитися списком',

    // Payment Page
    noPaymentMethods: 'Немає платіжних методів',
    noPaymentMethodsDesc: 'Ви ще не зберегли жодного платіжного методу. Додайте кредитну або дебетову картку для швидшого оформлення замовлень у майбутньому.',
    addPaymentMethodBtn: 'Додати платіжний метод',

    // Compare Products Page
    nothingToCompare: 'Нічого порівнювати',
    nothingToCompareDesc: 'Ви ще не додали жодного товару для порівняння. Перегляньте наш каталог, щоб знайти товари для порівняння.',

    // Orders Page
    allOrdersFilter: 'Всі замовлення',
    statusCompleted: 'Виконано',
    statusInProcessing: 'В обробці',
    statusCancelled: 'Скасовано',
    statusAwaitingShipment: 'Очікує відправки',
    orderSearchPlaceholder: 'Пошук замовлень',
    noOrdersFound: 'Замовлень не знайдено.',
    orderId: 'ID замовлення',
    totalLabel: 'Всього',
    orderTotal: 'Сума замовлення',
    orderDate: 'Дата замовлення',
    deliveryDateLabel: 'Дата доставки',
    sellerLabel: 'Продавець',
    leaveReviewBtn: 'Залишити відгук',
    reorderBtn: 'Повторити замовлення',
    refundsBtn: 'Повернення',
    clear: 'Очистити',
    moreItems: 'більше товарів...',
    statusLabel: 'Статус',
    itemsAddedToCart: 'Товари додано в кошик',
    refundReasonDefects: 'Виявлено дефекти або пошкодження',
    refundReasonNonCompliance: 'Невідповідність заявленим характеристикам',
    refundReasonMissing: 'Відсутня заявлена комплектація або функції',

    // Message Page Tabs & Content
    messagesAll: 'Всі повідомлення',
    messagesUnread: 'Непрочитані',
    messagesArchived: 'Архів',
    messagesSaved: 'Збережені',
    noMessages: 'Тут немає повідомлень',
    sendAMessage: 'Надіслати повідомлення',
    markAsUnread: 'Позначити як непрочитане',
    archiveDiscussion: 'Архівувати діалог',
    deleteDiscussion: 'Видалити діалог',
    toFixDiscussion: 'Закріпити діалог',
    saveDiscussion: 'Зберегти діалог',
    selectChatToStart: 'Оберіть чат для листування',

    // Settings Page (Change Password & Notifications)
    changePasswordTitle: 'Зміна паролю',
    oldPasswordLabel: 'Старий пароль',
    newPasswordLabel: 'Новий пароль',
    confirmNewPasswordLabel: 'Підтвердіть новий пароль',
    updatePasswordBtn: 'Оновити пароль',
    notificationSettings: 'Налаштування сповіщень',
    orderStatusNotifications: 'Статус замовлень',
    orderStatusDesc: 'Отримувати сповіщення про зміну статусу вашого замовлення',
    promoNotifications: 'Акції та пропозиції',
    promoDesc: 'Сповіщення про знижки, розпродажі та персональні промокоди',
    securityNotifications: 'Безпека акаунту',
    securityDesc: 'Важливі повідомлення про вхід з нових пристроїв та зміну паролю',
    fillAllFields: 'Будь ласка, заповніть усі поля для паролю.',
    passwordsDoNotMatch: 'Паролі не збігаються.',
    passwordChangedSuccess: 'Пароль успішно змінено!',
    passwordChangeFailed: 'Не вдалося змінити пароль.',
    saving: 'Збереження...',

    // Help & FAQ Section
    faqTitle: 'Часті запитання (FAQ)',
    faq1Q: 'Як я можу відстежити своє замовлення?',
    faq1A: 'Ви можете відстежувати статус замовлення безпосередньо у своєму кабінеті в розділі "Мої замовлення" або за посиланням для відстеження, надісланим на вашу пошту.',
    faq2Q: 'Які способи оплати підтримуються?',
    faq2A: 'Ми приймаємо картки Visa, Mastercard, Apple Pay, Google Pay та оплату при отриманні (післяплата).',
    faq3Q: 'Як мені повернути товар?',
    faq3A: 'Ви можете оформити запит на повернення протягом 14 днів з моменту отримання товару через розділ підтримки або звернувшись до продавця.',
    faq4Q: 'Як зв\'язатися з продавцем напряму?',
    faq4A: 'Перейдіть на сторінку товару або в деталі вашого замовлення та натисніть "Повідомлення продавцю", щоб відкрити прямий чат.',
    contactSupportTitle: 'Потрібна додаткова допомога?',
    contactSupportDesc: 'Надішліть нам повідомлення, і наша служба підтримки відповість протягом 24 годин.',
    subjectLabel: 'Тема',
    subjectPlaceholder: 'напр., Питання щодо замовлення #1234',
    messageLabel: 'Повідомлення',
    messagePlaceholder: 'Детально опишіть ваше питання або проблему...',
    sending: 'Надсилання...',
    sendSupportRequestBtn: 'Надіслати повідомлення',
    supportTicketCreated: 'Запит до служби підтримки надіслано! Наша команда зв\'яжеться з вами найближчим часом.',

    // FooterSeller
    startSelling: 'Почніть продавати вже сьогодні!',
    sellSubtitle: 'Приєднуйтесь до нашого маркетплейсу та відкривайте нові можливості для вашого бізнесу!',
    sellPoint1: 'Мільйони покупців вже чекають на ваші товари;',
    sellPoint2: 'Збільшуйте продажі та отримуйте більше прибутку;',
    sellPoint3: 'Зручна панель керування та інструменти зростання',
    sellButton: 'Стати продавцем',
    
    // Footer
    deliveryPayment: 'Доставка та оплата',
    guarantee: 'Гарантія',
    productReturn: 'Повернення товару',
    support: 'Підтримка',
    news: 'Новини',
    marketplaceGuide: 'Гід по маркетплейсу',
    copyright: '© Easybuy.2024 Всі права захищені',
    privacyPolicy: 'Політика конфіденційності',
    userAgreement: 'Угода користувача',

    // MobileMenu
    close: 'Закрити',
    back: 'Назад',
    notEmpty: 'Немає товарів',
    selectCategory: 'Оберіть категорію →',
    selectSubcategory: 'Оберіть підкатегорію →',

    // Home Page
    favoriteBrands: 'Улюблені бренди',
    ukrainianBrands: 'Українські Бренди',
    recommendations: 'Рекомендації',
    shopNow: 'Купити зараз',
    onSale: 'Знижка',
    addToCart: 'В кошик',
    christmasSale: 'Різдвяний розпродаж',
    upTo33: 'Знижки до -33%',
    
    // Promo Slider
    promoTitle1: 'Літня колекція',
    promoDesc1: 'Відкрийте для себе найгарячіші купальники сезону',
    promoTitle2: 'Морський стиль',
    promoDesc2: 'Ексклюзивний пляжний одяг для вашого ідеального відпочинку',

    // Catalog & Filters
    home: 'Головна',
    allProducts: 'Всі товари',
    allFilters: 'Всі фільтри',
    price: 'Ціна',
    brand: 'Бренд',
    size: 'Розмір',
    color: 'Колір',
    material: 'Матеріал',
    discount: 'Знижка',
    rating: 'Рейтинг',
    sort: 'Сортувати',
    subscribe: 'Підписатися',
    subscribeSearches: 'Підписатися на оновлення',
    activeFilters: 'Активні фільтри',
    resetAll: 'Скинути все',
    noProductsFound: 'Товарів не знайдено',
    tryResettingFilters: 'Спробуйте змінити або скинути обрані фільтри',
    loadingCatalogue: 'Завантаження каталогу...',
    
    // Sort Options
    fromCheapToExpensive: 'Від дешевих до дорогих',
    fromExpensiveToCheap: 'Від дорогих до дешевих',
    byPopularity: 'За популярністю',
    byNovelty: 'За новинками',

    // Checkout Flow Keys
    checkoutTitle: 'Оформлення замовлення',
    stepContacts: 'Контакти',
    stepDelivery: 'Доставка',
    stepDiscounts: 'Знижки',
    stepPayment: 'Оплата',
    authDesc: 'Увійдіть до особистого кабінету, щоб отримати персональні бонуси',
    loginToCabinet: 'Увійти в кабінет',
    continueWithoutAuth: 'Продовжити як гість',
    continueShopping: 'Продовжити покупки',
    placeOrder: 'Оформити замовлення',
    nextStep: 'Далі',
    prevStep: 'Назад',
    deliveryMethod: 'Спосіб доставки',
    novaPoshtaBranch: 'Нова Пошта (Відділення / Поштомат)',
    novaPoshtaCourier: 'Нова Пошта (Кур’єрська доставка)',
    ukrPoshtaBranch: 'Укрпошта (Відділення)',
    pickup: 'Самовивіз з точки видачі',
    cityLabel: 'Місто доставки',
    cityPlaceholder: 'Київ',
    branchLabel: 'Номер відділення або поштомату',
    branchPlaceholder: 'Відділення № 25 (вул. Хрещатик, 1)',
    addressLabel: 'Адреса (вулиця, будинок, квартира)',
    addressPlaceholder: 'вул. Тараса Шевченка, 10, кв. 25',
    recipientChoice: 'Отримувач',
    recipientMyself: 'Я є отримувачем',
    recipientAnother: 'Інша особа',
    recipientNameLabel: 'Ім’я та прізвище отримувача',
    recipientPhoneLabel: 'Телефон отримувача',
    promoCodeTitle: 'Промокод або сертифікат',
    promoCodePlaceholder: 'Введіть промокод (напр. EASYBUY10)',
    applyPromo: 'Застосувати',
    promoApplied: 'Промокод на -10% успішно застосовано!',
    promoInvalid: 'Недійсний промокод',
    paymentMethod: 'Спосіб оплати',
    cardOnline: 'Оплата онлайн (Visa / Mastercard / Stripe)',
    cashOnDelivery: 'Оплата при отриманні (післяплата)',
    commentLabel: 'Коментар до замовлення',
    commentPlaceholder: 'Побажання щодо доставки або упакування...',
    callMeBackLabel: 'Не перетелефоновувати для підтвердження',
    orderSuccessTitle: 'Дякуємо за замовлення!',
    orderSuccessDesc: 'Ваше замовлення успішно прийнято в обробку.',
    orderNumberLabel: 'Номер замовлення',
    orderSuccessEmailNotice: 'Деталі та статус відправлено на вашу електронну пошту.',
    backToCatalog: 'Повернутися до покупок',

    // Product Details Page Keys
    productDescriptionTab: 'Опис',
    characteristicsTab: 'Характеристики',
    paymentTab: 'Оплата',
    photosTab: 'Фото',
    shippingTab: 'Доставка',
    customerReviewsTitle: 'Відгуки покупців',
    leaveReviewBtn: 'Залишити відгук',
    sellerPrefix: 'Продавець',
    shopStore: 'Магазин',
    buyNowBtn: 'Купити в 1 клік',
    sizeGuideBtn: 'Таблиця розмірів',
    modelSizeNotice: 'Зріст моделі 172 см, розмір на фото: S',
    articleLabel: 'Артикул',
    colorLabel: 'Колір',
    sizeLabel: 'Розмір',
    youMayAlsoLikeTitle: 'Вам також може сподобатися',
    linkCopiedToast: 'Посилання на товар скопійовано!',
    pleaseSelectSizeToast: 'Будь ласка, оберіть розмір товару',
    addedToCartToast: 'Товар успішно додано до кошика!',
    reviewsCountSuffix: 'відгуків',
    productStoryTitle: 'Історія та опис моделі',
    featuresBenefitsTitle: 'Особливості та переваги',
    detailsTitle: 'Деталі товару',
    materialInfoTitle: 'Інформація про матеріали',
    careInstructionsTitle: 'Рекомендації з догляду',
    paymentInfoTitle: 'Інформація про оплату',
    paymentMethodsListTitle: 'Способи оплати',
    standardDeliveryTitle: 'Стандартна доставка',
    standardDeliveryDesc: 'Доставка кур’єром або у відділення протягом 1-3 робочих днів.',
    expressDeliveryTitle: 'Експрес-доставка',
    expressDeliveryDesc: 'При замовленні до 14:00 — відправка в день замовлення.',

    // Favorites Page Keys
    favoritesPageTitle: 'Список бажань та обране',
    emptyFavoritesTitle: 'Ваш список бажань порожній',
    emptyFavoritesDesc: 'Додавайте вподобані товари, натиснувши на іконку сердечка, щоб зберегти їх на потім.',
    addAllToCart: 'Перемістити все в кошик',
    clearWishlist: 'Очистити список',
    allMovedToCartToast: 'Всі збережені товари додано до вашого кошика!',
    wishlistClearedToast: 'Список бажань очищено',
    itemsInWishlistCount: 'товарів у списку',

    // Store Page Keys
    storeProductsTab: 'Товари магазину',
    storeAboutTab: 'Про магазин',
    storeReviewsTab: 'Відгуки про магазин',
    subscribeStore: 'Підписатися',
    subscribedStore: 'Ви підписані',
    contactSeller: 'Написати продавцю',
    verifiedSellerBadge: 'Перевірений продавець',
    storeSalesCount: 'успішних продажів',
    storeRating: 'рейтинг продавця',
    storeSince: 'На платформі з',
    searchInStore: 'Пошук серед товарів магазину...',
    storeLocation: 'Місцезнаходження',
    businessType: 'Тип діяльності',
    manufacturerType: 'Виробник',
    traderType: 'Торгова компанія',
    warrantyAndReturns: 'Гарантія та повернення',
    warrantyAndReturnsDesc: '14 днів на повернення або обмін згідно із Законом України «Про захист прав споживачів».',

    // Seller Dashboard & Add Product Keys
    sellerProducts: 'Товари',
    availableToOrder: 'Доступно до замовлення',
    outOfStock: 'Немає в наявності',
    review: 'На модерації',
    implementationStatus: 'Статус реалізації',
    initialQty: 'Початкова кількість',
    soldQty: 'Кількість проданих одиниць',
    stockAvailability: 'Наявність на складі',
    remainder: 'Залишок (шт)',
    productCode: 'Артикул товару',
    generalInformation: 'Загальна інформація',
    sellerGeneralOverview: 'Загальний огляд',
    imageUploadTitle: 'Головне фото товару',
    imageUploadTip: 'Перетягніть фото сюди або клікніть для вибору файлу',
    variations: 'Варіації та параметри',
    chooseColor: 'Оберіть кольори',
    chooseSize: 'Оберіть розміри',
    visibility: 'Видимість товару',
    published: 'Опубліковано',
    draft: 'Чернетка',
    hidden: 'Приховано',
    deleteSelected: 'Видалити обрані',
    deactivate: 'Деактивувати',
    update: 'Зберегти зміни',
    options: 'Опції / Варіанти',
    productRating: 'Рейтинг товару',
    season: 'Сезон',
    material: 'Матеріал',
    export: 'Експорт',
    filter: 'Фільтр',
    showMore: 'Показати більше',

    // Audit Discovered Missing Keys
    sendResetLinkBtn: 'Надіслати посилання для скидання',
    resetPasswordTitle: 'Скидання пароля',
    resetPasswordSub: 'Введіть вашу електронну пошту для отримання інструкцій',
    backToLoginBtn: 'Повернутися до входу',
    sendingText: 'Надсилання...',
    itemsCount: 'товарів',
    itemCount: 'товар',
    deleteAll: 'Видалити все',
    cartTitle: 'Кошик',
    category: 'Категорія',
    addedToFavorites: 'Додано до обраного',
    removedFromFavorites: 'Видалено з обраного',
    brands: 'Бренди',
    sizes: 'Розміри',
    colors: 'Кольори',
    reset: 'Скинути',
    onlyDiscounts: 'Тільки зі знижкою',
    searchBrand: 'Пошук бренду...',
    filters: 'Фільтри',
    applyFilters: 'Застосувати фільтри',
    selectFromList: 'Оберіть зі списку',
    yourRating: 'Ваша оцінка',
    returnReason: 'Причина повернення',
    refundSuccessTitle: 'Заявку на повернення прийнято!',
    refundSuccessDesc: 'Менеджер зв’яжеться з вами протягом 1 робочого дня.',
    reviewSuccessTitle: 'Дякуємо за відгук!',
    reviewSuccessDesc: 'Ваш відгук успішно опубліковано.',
    productReturnTitle: 'Повернення товару за замовленням #',
    sendReviewBtn: 'Надіслати відгук',
    nameLabel: 'Ваше ім’я',
    namePlaceholder: 'Олександр',
    writeReview: 'Напишіть ваші враження від товару...',
    additionalInfo: 'Додаткова інформація',
    leaveReviewTitle: 'Залишити відгук до замовлення #',
    promoTitle3: 'Осінній затишок',
    promoDesc3: 'Нова колекція теплих светрів та стильних курток',
    checkEmailTitle: 'Перевірте вашу пошту',
    checkEmailDesc: 'Ми надіслали інструкції для підтвердження на вашу електронну адресу.',
    goToLogin: 'Перейти до входу',
    backToHome: 'На головну',
    signUpAction: 'Зареєструватися',
    dontHaveAccount: 'Немає акаунту?',
    backToMenu: 'До меню',
    cart: 'Кошик',
    newPasswordTitle: 'Відновлення паролю',
    enterNewPasswordSub: 'Введіть новий пароль для вашого облікового запису.',
    newPasswordPlaceholder: 'Введіть новий пароль',
    confirmNewPasswordPlaceholder: 'Підтвердіть новий пароль',
    confirm: 'Підтвердити',
    resetting: 'Оновлення пароля...',
    passwordResetSuccess: 'Пароль успішно відновлено!',
    passwordReqMin: 'Пароль повинен містити щонайменше 6 символів',
    passwordReqMax: 'Пароль не повинен перевищувати 50 символів',
    passwordReqLower: 'Пароль повинен містити хоча б одну малу літеру',
    passwordReqUpper: 'Пароль повинен містити хоча б одну велику літеру',
    passwordReqNumber: 'Пароль повинен містити хоча б одну цифру',
    passwordReqSpecial: 'Пароль повинен містити хоча б один спеціальний символ',
    passwordReqMatch: 'Паролі повинні збігатися',
    passwordReqRequired: 'Обов’язкове поле',
    confirmPasswordRequired: 'Будь ласка, підтвердіть пароль',
  },
  en: {
    catalogue: 'Catalog',
    contacts: 'Contacts',
    sale: 'Sale',
    searchPlaceholder: 'Search stores, products, users, orders...',
    searchButton: 'Search',
    signUp: 'Sign up',
    favorites: 'Favorites',
    myProfile: 'My Profile',
    logOut: 'Log Out',
    logIn: 'Log In',

    // Auth & Sign Up Form Keys
    signUpTitle: 'Sign Up',
    emailLabel: 'Email',
    emailPlaceholder: 'example@email.com',
    phoneNumberLabel: 'Phone Number',
    phoneNumberPlaceholder: '+380991234567',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    confirmPasswordLabel: 'Confirm Password',
    confirmPasswordPlaceholder: '••••••••',
    userAgreementLink: 'I accept User Agreement',
    privacyPolicyLink: 'I accept Privacy Policy',
    confirmBtn: 'Sign Up',
    alreadyHaveAccount: 'Already have an account?',
    logInAction: 'Log In',
    logInTitle: 'Log In',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginSuccess: 'Login successful',
    loginFailed: 'Invalid email or password',
    loginError: 'An unknown error occurred during login',
    registrationFailed: 'Registration failed.',
    registrationError: 'An unknown error occurred during registration',
    loadingText: 'Loading...',

    // Buyer Profile Panel Sidebar
    personalData: 'Personal Data',
    myOrders: 'My Orders',
    cartMenu: 'Cart',
    message: 'Messages',
    wishlist: 'Wishlist',
    productsToCompare: 'Compare',
    payment: 'Payment',
    settings: 'Settings',
    helpCenter: 'Support & FAQ',

    // Seller Dashboard Menu
    sellerHome: 'Home panel',
    sellerProducts: 'Products',
    sellerOrders: 'Order',
    sellerChat: 'Chat with customers',
    sellerReviews: 'Reviews',
    sellerNotifications: 'Notification',
    sellerSettings: 'Profile settings',
    sellerManagers: 'Managers',
    sellerPromotions: 'Promotions',
    sellerSupport: 'Technical support',

    // Seller Cabinet Translations (EN)
    sellerGeneralOverview: 'General overview',
    last30days: 'Last 30 days',
    last7days: 'Last 7 days',
    numberOfOrders: 'Number of orders',
    storeRating: 'Store rating',
    storeViews: 'Views',
    storePageViews: 'Store page views',
    productViews: 'Product views',
    interaction: 'Interaction',
    addedToCart: 'Items added to cart',
    ordersPlaced: 'Orders placed',
    incomeUah: 'Income, UAH',
    generalInformation: 'General information',
    period: 'Period',
    incomeAmount: 'Income amount',
    itemsSold: 'Number of items sold',
    activeOrdersCount: 'Number of active orders',
    completedOrdersCount: 'Number of completed orders',
    export: 'Export',
    allProducts: 'All',
    deleteSelected: 'Delete Selected',
    filter: 'Filter',
    sort: 'Sort',
    addProduct: 'Add',
    productName: 'Product Name',
    productCode: 'Product code',
    remainder: 'Remainder',
    options: 'Options',
    implementationStatus: 'Implementation status',
    showMore: 'Show more',
    back: 'Back',
    editProduct: 'Edit Product',
    variations: 'Options',
    chooseColor: 'Choose a color',
    chooseSize: 'Choose size',
    deactivate: 'Deactivate',
    update: 'Update',
    availableToOrder: 'Available to order',
    review: 'Review',
    outOfStock: 'Out of stock',
    createOrder: 'Create order',
    client: 'Client',
    orderNumber: 'Order number',
    description: 'Description',
    delivery: 'Delivery',
    paymentStatus: 'Payment',
    commentOnOrder: 'Comment on the order',
    unpaid: 'Unpaid',
    paid: 'Paid',
    newOrder: 'New',
    delivered: 'Delivered',
    completed: 'Completed',
    clientInfo: 'Client information',
    deliveryAddress: 'Delivery address',
    country: 'Country',
    cityVillage: 'City/Village',
    address: 'Address',
    novaPoshtaBranch: 'Nova Poshta branch',
    quantityPcs: 'Quantity pcs',
    size: 'Size',
    color: 'Color',
    total: 'Total',
    allChats: 'All chats',
    sendAMessage: 'Type a message...',
    selectChatToStart: 'Select a chat',
    chooseChatFromList: 'Choose a conversation from the list to start messaging.',
    send: 'Send',
    positiveScore: 'Positive score',
    ratingDetailsByReviews: 'Rating details by reviews',
    periodTable: 'Period',
    oneMonth: '1 Month',
    sixMonths: '6 Months',
    twelveMonths: '12 Months',
    positiveReviews: 'Positive',
    neutralReviews: 'Neutral',
    negativeReviews: 'Negative',
    replyToCustomer: 'Reply to customer feedback...',
    reply: 'Reply',
    you: 'You',
    clearAll: 'Clear all',
    noNotifications: 'No notifications',
    companyInfo: 'Company information',
    companyName: 'Company name',
    aboutCompany: 'About the company',
    additionalInformation: 'Additional information',
    businessType: 'Business type',
    employeesCount: 'Employees count',
    foundationYear: 'Foundation year',
    location: 'Location',
    settingsSaved: 'Profile settings updated!',
    saving: 'Saving...',
    addManager: 'Add Manager',
    role: 'Role',
    remove: 'Remove',
    createPromotion: 'Create a promotion',
    validityPeriod: 'Validity period',
    value: 'Value',
    actions: 'Actions',
    choosePromoType: 'Choose a promotion type',
    basicInformation: 'Basic information',
    startDate: 'Start Date',
    endDate: 'End Date',
    technicalSupport: 'Technical support',
    contactUs: 'Contact us',
    faq: 'FAQ',
    planned: 'Planned',
    active: 'Active',
    edit: 'Edit',
    delete: 'Delete',
    producer: 'Producer',
    trader: 'Trading company',
    callCenter: 'Call Center',
    telegramChat: 'Telegram Chat',
    whatsappChat: 'WhatsApp Chat',
    visibility: 'Visibility',
    published: 'Published',
    draft: 'Draft',
    hidden: 'Hidden',
    initialQty: 'Initial quantity',
    soldQty: 'Number of units sold',
    stockAvailability: 'Availability of stock',
    productRating: 'Product rating',
    season: 'Season',
    material: 'Material',
    imageUploadTitle: 'Main Image',
    imageUploadTip: 'Drag and drop or click to upload',


    // Personal Data Page & Form Editing
    userData: 'Personal Data',
    addressData: 'Shipping Address',
    dateOfBirth: 'Date of Birth',
    profilePhone: 'Phone',
    profileName: 'Name',
    profileEmail: 'Email',
    country: 'Country',
    city: 'City',
    address: 'Street and House',
    cancelBtn: 'Cancel',
    saveBtn: 'Save',
    loadingProfile: 'Loading profile...',

    // Cart Page
    emptyCartTitle: 'Your cart is empty',
    emptyCartDesc: 'Looks like you haven\'t added anything to your cart yet',
    goToShopping: 'GO TO SHOPPING',
    allItems: 'All items',
    summary: 'Summary',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    checkoutTitle: 'Checkout',
    deleteItemTitle: 'Delete item?',
    deleteItemDesc: 'Are you sure you want to remove this item from your cart?',
    deleteItemYes: 'Yes, remove',
    deleteItemNo: 'No, keep',
    viewedProducts: 'Products you viewed',
    noViewedProducts: 'No viewed products',

    // Wishlist Page
    wishlistEmptyTitle: 'Your wishlist is empty',
    wishlistEmptyDesc: 'Products you mark with a heart will appear here',
    catalogueBtn: 'Go to Catalogue',
    shareWishlist: 'Share Wishlist',

    // Payment Page
    noPaymentMethods: 'No payment methods',
    noPaymentMethodsDesc: 'You don\'t have any saved payment methods yet. Add a credit or debit card for faster checkout in the future.',
    addPaymentMethodBtn: 'Add Payment Method',

    // Compare Products Page
    nothingToCompare: 'Nothing to compare',
    nothingToCompareDesc: 'You haven\'t added any products to compare yet. Browse our catalogue to find items you\'d like to compare side-by-side.',

    // Orders Page
    allOrdersFilter: 'All orders',
    statusCompleted: 'Completed',
    statusInProcessing: 'In processing',
    statusCancelled: 'Cancelled',
    statusAwaitingShipment: 'Awaiting shipment',
    orderSearchPlaceholder: 'Order search',
    noOrdersFound: 'No orders found.',
    orderId: 'Order ID',
    totalLabel: 'Total',
    orderTotal: 'Order Total',
    orderDate: 'Order Date',
    deliveryDateLabel: 'Delivery date',
    sellerLabel: 'Seller',
    leaveReviewBtn: 'Leave a review',
    reorderBtn: 'Reorder',
    refundsBtn: 'Refunds',
    clear: 'Clear',
    moreItems: 'more items...',
    statusLabel: 'Status',
    itemsAddedToCart: 'Items added to cart',
    refundReasonDefects: 'Defects or damage have been detected',
    refundReasonNonCompliance: 'Non-compliance with the declared characteristics',
    refundReasonMissing: 'The declared equipment or functions are missing',

    // Message Page Tabs & Content
    messagesAll: 'All',
    messagesUnread: 'Unread',
    messagesArchived: 'Archived',
    messagesSaved: 'Saved',
    noMessages: 'No messages here',
    sendAMessage: 'Send a message',
    markAsUnread: 'Mark as unread',
    archiveDiscussion: 'Archive discussion',
    deleteDiscussion: 'Delete discussion',
    toFixDiscussion: 'Pin discussion',
    saveDiscussion: 'Save discussion',
    selectChatToStart: 'Select a chat to start messaging',

    // Settings Page (Change Password & Notifications)
    changePasswordTitle: 'Change Password',
    oldPasswordLabel: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmNewPasswordLabel: 'Confirm New Password',
    updatePasswordBtn: 'Update Password',
    notificationSettings: 'Notification Preferences',
    orderStatusNotifications: 'Order Status Updates',
    orderStatusDesc: 'Receive email notifications when your order status changes',
    promoNotifications: 'Promotions & Discounts',
    promoDesc: 'Get special offers and discount codes',
    securityNotifications: 'Security Alerts',
    securityDesc: 'Important security notifications regarding your account',
    fillAllFields: 'Please fill in all password fields.',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordChangedSuccess: 'Password changed successfully!',
    passwordChangeFailed: 'Failed to change password.',
    saving: 'Saving...',

    // Help & FAQ Section
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'How can I track my order?',
    faq1A: 'You can track your order status directly in your account under the "My Orders" section or via the tracking link sent to your email.',
    faq2Q: 'What payment methods are supported?',
    faq2A: 'We accept Visa, Mastercard, Apple Pay, Google Pay, and Cash on Delivery (COD).',
    faq3Q: 'How do I return a product?',
    faq3A: 'You can initiate a return request within 14 days of receiving your item via the "Refunds" section in your buyer cabinet.',
    faq4Q: 'How do I contact a seller directly?',
    faq4A: 'Go to the product page or your order details and click "Message Seller" to open a direct chat thread.',
    contactSupportTitle: 'Need Further Help?',
    contactSupportDesc: 'Send us a message and our support team will respond within 24 hours.',
    subjectLabel: 'Subject',
    subjectPlaceholder: 'e.g., Question about my order #1234',
    messageLabel: 'Message',
    messagePlaceholder: 'Describe your issue or question in detail...',
    sending: 'Sending...',
    sendSupportRequestBtn: 'Send Message',
    supportTicketCreated: 'Support request sent! Our team will get back to you shortly.',
    
    // FooterSeller
    startSelling: 'Start selling today!',
    sellSubtitle: 'Join our marketplace and discover new opportunities for your business!',
    sellPoint1: 'Millions of buyers are waiting for your products;',
    sellPoint2: 'Increase sales and make more profit;',
    sellPoint3: 'User-friendly control panel and growth tools',
    sellButton: 'Sell Your Item',
    
    // Footer
    deliveryPayment: 'Delivery and payment',
    guarantee: 'Guarantee',
    productReturn: 'Product return',
    support: 'Support',
    news: 'News',
    marketplaceGuide: 'Marketplace Guide',
    copyright: '© Easybuy.2024 All rights reserved',
    privacyPolicy: 'Privacy Policy',
    userAgreement: 'User Agreement',

    // MobileMenu
    close: 'Close',
    back: 'Back',
    notEmpty: 'No items',
    selectCategory: 'Select a category →',
    selectSubcategory: 'Select a subcategory →',

    // Home Page
    favoriteBrands: 'Favorite brands',
    ukrainianBrands: 'Ukrainian Brands',
    recommendations: 'Recommendations',
    shopNow: 'Shop now',
    onSale: 'On Sale',
    addToCart: 'Add to Cart',
    christmasSale: 'Christmas Sale',
    upTo33: 'Up to -33%',
    
    // Promo Slider
    promoTitle1: 'Summer Collection',
    promoDesc1: 'Discover the hottest swimwear of the season',
    promoTitle2: 'Yacht Life',
    promoDesc2: 'Exclusive beachwear for your perfect vacation',

    // Catalog & Filters
    home: 'Home',
    allProducts: 'All products',
    allFilters: 'All Filters',
    price: 'Price',
    brand: 'Brand',
    size: 'Size',
    color: 'Color',
    material: 'Material',
    discount: 'Discount',
    rating: 'Rating',
    sort: 'Sort',
    subscribe: 'Subscribe',
    subscribeSearches: 'Subscribe your searches',
    activeFilters: 'Active filters',
    resetAll: 'Reset all',
    noProductsFound: 'No products found',
    tryResettingFilters: 'Try resetting or adjusting your selected filters',
    loadingCatalogue: 'Loading catalogue...',

    // Sort Options
    fromCheapToExpensive: 'from cheap to expensive',
    fromExpensiveToCheap: 'from expensive to cheap',
    byPopularity: 'by popularity',
    byNovelty: 'by novelty',

    // Checkout Flow Keys
    checkoutTitle: 'Checkout',
    stepContacts: 'Contacts',
    stepDelivery: 'Delivery',
    stepDiscounts: 'Discounts',
    stepPayment: 'Payment',
    authDesc: 'Sign in to your personal account for member bonuses',
    loginToCabinet: 'Log In',
    continueWithoutAuth: 'Continue as guest',
    continueShopping: 'Continue Shopping',
    placeOrder: 'Place Order',
    nextStep: 'Next',
    prevStep: 'Back',
    deliveryMethod: 'Delivery Method',
    novaPoshtaBranch: 'Nova Poshta (Branch / Parcel Locker)',
    novaPoshtaCourier: 'Nova Poshta (Courier Delivery)',
    ukrPoshtaBranch: 'Ukrposhta (Branch)',
    pickup: 'Self-pickup from store',
    cityLabel: 'Delivery City',
    cityPlaceholder: 'Kyiv',
    branchLabel: 'Branch or Parcel Locker Number',
    branchPlaceholder: 'Branch #25 (Khreshchatyk st., 1)',
    addressLabel: 'Address (street, building, apt)',
    addressPlaceholder: 'Taras Shevchenko st., 10, apt. 25',
    recipientChoice: 'Recipient',
    recipientMyself: 'I am the recipient',
    recipientAnother: 'Another person',
    recipientNameLabel: 'Recipient Full Name',
    recipientPhoneLabel: 'Recipient Phone',
    promoCodeTitle: 'Promo Code or Gift Card',
    promoCodePlaceholder: 'Enter promo code (e.g. EASYBUY10)',
    applyPromo: 'Apply',
    promoApplied: 'Promo code for -10% discount applied!',
    promoInvalid: 'Invalid promo code',
    paymentMethod: 'Payment Method',
    cardOnline: 'Pay online with card (Visa / Mastercard / Stripe)',
    cashOnDelivery: 'Cash on delivery',
    commentLabel: 'Order Comment',
    commentPlaceholder: 'Any specific requests or packaging notes...',
    callMeBackLabel: 'Do not call back to confirm order',
    orderSuccessTitle: 'Thank you for your order!',
    orderSuccessDesc: 'Your order has been successfully placed.',
    orderNumberLabel: 'Order Number',
    orderSuccessEmailNotice: 'Order details and tracking status have been sent to your email.',
    backToCatalog: 'Back to Shopping',

    // Product Details Page Keys
    productDescriptionTab: 'Description',
    characteristicsTab: 'Characteristics',
    paymentTab: 'Payment',
    photosTab: 'Photos',
    shippingTab: 'Shipping',
    customerReviewsTitle: 'Customer Reviews',
    leaveReviewBtn: 'Leave a Review',
    sellerPrefix: 'Seller',
    shopStore: 'Shop',
    buyNowBtn: 'Buy Now',
    sizeGuideBtn: 'Size Guide',
    modelSizeNotice: 'Model is 172 cm tall, wearing size S',
    articleLabel: 'Article',
    colorLabel: 'Color',
    sizeLabel: 'Size',
    youMayAlsoLikeTitle: 'You May Also Like',
    linkCopiedToast: 'Product link copied to clipboard!',
    pleaseSelectSizeToast: 'Please select a size first',
    addedToCartToast: 'Product added to cart!',
    reviewsCountSuffix: 'reviews',
    productStoryTitle: 'Product Story',
    featuresBenefitsTitle: 'Features & Benefits',
    detailsTitle: 'Product Details',
    materialInfoTitle: 'Material Information',
    careInstructionsTitle: 'Care Instructions',
    paymentInfoTitle: 'Payment Information',
    paymentMethodsListTitle: 'Payment Methods',
    standardDeliveryTitle: 'Standard Delivery',
    standardDeliveryDesc: 'Delivery within 1-3 working days by courier or parcel locker.',
    expressDeliveryTitle: 'Express Delivery',
    expressDeliveryDesc: 'Order before 14:00 for same-day dispatch.',

    // Favorites Page Keys
    favoritesPageTitle: 'Wishlist & Favorites',
    emptyFavoritesTitle: 'Your wishlist is empty',
    emptyFavoritesDesc: 'Add products to your wishlist by clicking the heart icon to save them for later.',
    addAllToCart: 'Move all to cart',
    clearWishlist: 'Clear wishlist',
    allMovedToCartToast: 'All saved items have been added to your cart!',
    wishlistClearedToast: 'Wishlist cleared',
    itemsInWishlistCount: 'items in wishlist',

    // Store Page Keys
    storeProductsTab: 'Store Products',
    storeAboutTab: 'About Store',
    storeReviewsTab: 'Store Reviews',
    subscribeStore: 'Follow Store',
    subscribedStore: 'Following',
    contactSeller: 'Message Seller',
    verifiedSellerBadge: 'Verified Seller',
    storeSalesCount: 'successful sales',
    storeRating: 'seller rating',
    storeSince: 'On marketplace since',
    searchInStore: 'Search products in this store...',
    storeLocation: 'Location',
    businessType: 'Business Type',
    manufacturerType: 'Manufacturer',
    traderType: 'Trading Company',
    warrantyAndReturns: 'Warranty & Returns',
    warrantyAndReturnsDesc: '14 days return policy according to consumer protection legislation.',

    // Seller Dashboard & Add Product Keys
    sellerProducts: 'Products',
    availableToOrder: 'Available to order',
    outOfStock: 'Out of stock',
    review: 'Under Review',
    implementationStatus: 'Status',
    initialQty: 'Initial quantity',
    soldQty: 'Units sold',
    stockAvailability: 'Stock availability',
    remainder: 'Stock (pcs)',
    productCode: 'Product code / SKU',
    generalInformation: 'General information',
    sellerGeneralOverview: 'Overview',
    imageUploadTitle: 'Main product image',
    imageUploadTip: 'Drag & drop image here or click to browse',
    variations: 'Variations & Options',
    chooseColor: 'Select colors',
    chooseSize: 'Select sizes',
    visibility: 'Visibility',
    published: 'Published',
    draft: 'Draft',
    hidden: 'Hidden',
    deleteSelected: 'Delete Selected',
    deactivate: 'Deactivate',
    update: 'Save changes',
    options: 'Options',
    productRating: 'Product rating',
    season: 'Season',
    material: 'Material',
    export: 'Export',
    filter: 'Filter',
    showMore: 'Show more',

    // Audit Discovered Missing Keys
    sendResetLinkBtn: 'Send Reset Link',
    resetPasswordTitle: 'Reset Password',
    resetPasswordSub: 'Enter your email to receive recovery instructions',
    backToLoginBtn: 'Back to Login',
    sendingText: 'Sending...',
    itemsCount: 'items',
    itemCount: 'item',
    deleteAll: 'Clear all',
    cartTitle: 'Shopping Cart',
    category: 'Category',
    addedToFavorites: 'Added to favorites',
    removedFromFavorites: 'Removed from favorites',
    brands: 'Brands',
    sizes: 'Sizes',
    colors: 'Colors',
    reset: 'Reset',
    onlyDiscounts: 'Only discounts',
    searchBrand: 'Search brand...',
    filters: 'Filters',
    applyFilters: 'Apply Filters',
    selectFromList: 'Select from list',
    yourRating: 'Your Rating',
    returnReason: 'Return Reason',
    refundSuccessTitle: 'Refund request submitted!',
    refundSuccessDesc: 'Our support manager will contact you within 1 business day.',
    reviewSuccessTitle: 'Thank you for your review!',
    reviewSuccessDesc: 'Your review has been published.',
    productReturnTitle: 'Return order #',
    sendReviewBtn: 'Submit Review',
    nameLabel: 'Your Name',
    namePlaceholder: 'Alexander',
    writeReview: 'Write your feedback about this product...',
    additionalInfo: 'Additional information',
    leaveReviewTitle: 'Leave a review for order #',
    promoTitle3: 'Autumn Comfort',
    promoDesc3: 'New collection of cozy knitwear and stylish jackets',
    checkEmailTitle: 'Check Your Email',
    checkEmailDesc: 'We have sent confirmation instructions to your email address.',
    goToLogin: 'Go to Login',
    backToHome: 'Back to Home',
    signUpAction: 'Sign Up',
    backToMenu: 'Back to Menu',
    cart: 'Cart',
    newPasswordTitle: 'New Password',
    enterNewPasswordSub: 'Please enter and confirm your new password below.',
    newPasswordPlaceholder: 'Enter new password',
    confirmNewPasswordPlaceholder: 'Confirm new password',
    confirm: 'Confirm',
    resetting: 'Resetting...',
    passwordResetSuccess: 'Password reset successfully!',
    passwordReqMin: 'Password must be at least 6 characters long',
    passwordReqMax: 'Password cannot exceed 50 characters',
    passwordReqLower: 'Password must contain at least one lowercase letter',
    passwordReqUpper: 'Password must contain at least one uppercase letter',
    passwordReqNumber: 'Password must contain at least one number',
    passwordReqSpecial: 'Password must contain at least one special character',
    passwordReqMatch: 'Passwords must match',
    passwordReqRequired: 'Required',
    confirmPasswordRequired: 'Please confirm your password',
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState('ua');

  useEffect(() => {
    const savedLocale = localStorage.getItem('locale');
    if (savedLocale === 'ua' || savedLocale === 'en') {
      setLocale(savedLocale);
    } else {
      setLocale('ua');
      localStorage.setItem('locale', 'ua');
    }
  }, []);

  const changeLocale = (newLocale) => {
    if (newLocale === 'ua' || newLocale === 'en') {
      setLocale(newLocale);
      localStorage.setItem('locale', newLocale);
    }
  };

  const t = (key) => {
    return dictionary[locale]?.[key] || dictionary['ua']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale: changeLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      locale: 'ua',
      setLocale: () => {},
      t: (key) => dictionary['ua']?.[key] || key,
    };
  }
  return context;
};
